// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zpE8pIM05lNO-QpEjiJz35I8Rqg5fr0',
    appId: '1:64005452651:web:672dcf20895c506dbc122e',
    messagingSenderId: '64005452651',
    projectId: 'driveprep-3c0f0',
    authDomain: 'driveprep-3c0f0.firebaseapp.com',
    storageBucket: 'driveprep-3c0f0.firebasestorage.app',
    measurementId: 'G-WFPYTTNDJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4UcytxNVtzJFzTbmUoYS5vsTXcVYadE',
    appId: '1:64005452651:android:c01a117cddd509ccbc122e',
    messagingSenderId: '64005452651',
    projectId: 'driveprep-3c0f0',
    storageBucket: 'driveprep-3c0f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMO3WDhqQoaNCu5TPniMAumktFK2bAXE',
    appId: '1:64005452651:ios:89911be04136d47dbc122e',
    messagingSenderId: '64005452651',
    projectId: 'driveprep-3c0f0',
    storageBucket: 'driveprep-3c0f0.firebasestorage.app',
    iosBundleId: 'com.example.drivePrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMO3WDhqQoaNCu5TPniMAumktFK2bAXE',
    appId: '1:64005452651:ios:89911be04136d47dbc122e',
    messagingSenderId: '64005452651',
    projectId: 'driveprep-3c0f0',
    storageBucket: 'driveprep-3c0f0.firebasestorage.app',
    iosBundleId: 'com.example.drivePrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zpE8pIM05lNO-QpEjiJz35I8Rqg5fr0',
    appId: '1:64005452651:web:f08d7eb6043aea8bbc122e',
    messagingSenderId: '64005452651',
    projectId: 'driveprep-3c0f0',
    authDomain: 'driveprep-3c0f0.firebaseapp.com',
    storageBucket: 'driveprep-3c0f0.firebasestorage.app',
    measurementId: 'G-RMD0078Y8W',
  );
}
